### ISSUE TITLE
Plugin doesn't respect Grafana's theme

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#1]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2902918/194050900-bc81432c-bcf2-4da7-ad1a-7ddeb176c321.png">

**Comment by Loori-R** [comment]
Has been fixed in the commit 633cb309db8c916570ec56c74e1c6bf668bb843d

**Comment by Loori-R** [comment]
Commit 6767cd4f7656e4924db3450a8b05949400953296 should fix all issues with the theme.
