### ISSUE TITLE
Grafana v10 Angular plugin warning

### ISSUE THREAD

**Issue by asgeirn** [VictoriaMetrics/grafana-datasource#102]
Running Grafana v10.1.1 (0cfa76b22d) and victoriametrics-datasource v0.3.0 I get this warning in the query builder:

Angular plugin
This data source plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana.

[Read our deprecation notice and migration advice.](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/)

**Comment by Loori-R** [comment]
Thanks for the info! We'll work on fixing it.

**Comment by dmitryk-dk** [comment]
The issue was fixed and included in the [v0.5.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.5.0) release
