### ISSUE TITLE
WITH template cannot be added on not-yet saved dashboard

### ISSUE THREAD

**Issue by dg-nvm** [VictoriaMetrics/grafana-datasource#123]
If I create new dashboard and add WITH template, it will be saved without uid to datasource:

```
withTemplates": [
{
"expr": "commonLabels = {cloud=\"development\"}",
"uid": ""
}
```

This seems to not work and then template can't be found. If I save the dashboard and then create template, it will correctly fill uid:

```
{
"expr": "commonLabels={cloud=\"development\"}",
"uid": "test-dashboard-uid"
}
```

and WITH templates work.

**Comment by dmitryk-dk** [comment]
The issue was fixed and included in the the [v0.5.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.5.0) release
