### ISSUE TITLE
Issue with . in metrics names when editing query

### ISSUE THREAD

**Issue by matejsp** [VictoriaMetrics/grafana-datasource#128]
Victoria metrics supports metrics with dot in metrics name.
Based on the https://github.com/grafana/grafana/issues/42615
there is an issue with prometheus data provider.

We upgraded to victoria data source 0.5.0 but there is the same problem as with official prometheus data provider.

Creating new visualization:
<img width="1078" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/3091122/87972b84-358b-47d9-9e72-7d9784e18188">

Saving it. Reopening it:
<img width="2131" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/3091122/1441248e-f790-40d7-8c41-0ccb9d8b7f9a">

Metric name is CUT at . making it impossible to reselect or change any label filters.

Workaround with usePromCompatibleNaming works but the official data source should support . in a metric names.

**Comment by rul-hydro** [comment]
While this works for metrics with a dot, it will fail for the even weirder characters. I have metrics with slashes and dashes.
VMUI will switch from `my/metric` to `{__name__="my/metric"}` if it encounters crazy characters, but the datasource does not.

I can avoid this issue by setting a dummy metric name and writing the name into a label, but I would rather use the metric names directly for the benefits in grouping etc.

**Comment by Loori-R** [comment]
Both on VMUI and in datasources, when using the `/` character in a metric name, you can only retrieve this metric by using `{__name__="foo/bar"}`. If you simply enter `foo/bar`, the `/` character acts as a division operator and the query will not return metrics.

|   |   |
|---|---|
| ![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/29711459/02c4940d-e98f-4401-999d-78c7725995d1) | ![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/29711459/7fd37034-bc7d-4558-9e85-8358b5446acf) |
| ![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/29711459/627f5bec-95ac-4c82-bf5d-c2d55990c24a) | ![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/29711459/66049f43-9f4f-434f-87bd-9475f617f2bd) |

**Comment by rul-hydro** [comment]
You are right. I was mistaken in thinking that VMUI would distinguish between "clean" and "weird" metric names. The cardinality explorer always uses the `{__name__="foo"}` notation, which also avoids this problem.

In any case, it would be a cool feature if the query builder would pick the other notation if the metric name is not compatible with Prometheus naming conventions.

**Comment by matejsp** [comment]
It works for ".". We checked there is also problem with "-" that we use for some metrics. Shall we reopen or new ticket?

**Comment by Loori-R** [comment]
The symbol `-` is a minus operator. For example, for the query `foo-2`, the result will be a new set of time series data where each value of the metric `foo` is reduced by `2`. 
You can use `label filters` to make the query look like `{__name__="foo-2"}`.

**Comment by matejsp** [comment]
Yes using filter is fine ... The question is if we should support that query builder uses it automatically.

For example when selecting such metric from dropdown ... 
I can select the metric with "-" just fine ... 

<img width="2122" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/3091122/fe795c7b-c029-4818-8d00-5b2318482b3d">


Imho query builder should output the query as label filter in such cases ... or after selection it should change it to label filter: 

<img width="2140" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/3091122/b8809828-0955-43fe-9604-b0651fd44fd2">

**Comment by rul-hydro** [comment]
I'd say this is a new feature request (a very cool one). Will you post it or shall I?

**Comment by Loori-R** [comment]
Great feature, if it's not too much trouble, could you please create the request?

**Comment by matejsp** [comment]
I commented by suggesting far better and simpler solution in #131.
