### ISSUE TITLE
Wrong redirect link for Run in VMUI

### ISSUE THREAD

**Issue by ehuzii** [VictoriaMetrics/grafana-datasource#132]
Hello. judging by previous issues, the link is duplicated from the data source. but I see that the link is still generated incorrectly and does not work.
for example, in my case vmui host: `vm.infra.dev`
and correct ulr, if i want see my request in vmui: `vm.infra.dev/vmui/?g0.expr=request`
but grafana generate: `vm.infra.dev/graph?g0.expr=request`

this would work with Prometheus, but with vmui there is not enough path: `vmui` and `graph` suffix needs to be removed.

**Comment by hagen1778** [comment]
@Loori-R could you please take a look?

**Comment by hagen1778** [comment]
Hi @ehuzii! The issue was addressed in https://github.com/VictoriaMetrics/grafana-datasource/issues/132 and will be available in the next release. I'll keep this issue open until new release is cut.

**Comment by Loori-R** [comment]
This issue has been fixed in datasource starting from [v0.6.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.6.0). Closing the issue as fixed.
