### ISSUE TITLE
Error: Failed to build evaluator for queries and expressions: unable to find dependent node 'A'

### ISSUE THREAD

**Issue by ma-bo-panda** [VictoriaMetrics/grafana-datasource#134]
### What happened?
The following error message appears on the alert rule setup screen.
「Failed to build evaluator for queries and expressions: unable to find dependent node 'A'」
When I check the console in the developer tools, a 400 Bad Request is returned for a POST request to the API in api/v1/eval.
Also, the 400 error is repeated many times.

<img width="2297" alt="スクリーンショット 2024-01-19 22 11 57" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/157129874/6443d5b5-97af-4639-aff1-7abf86ca0505">

### What happened?
No errors are displayed on the alert rule setting screen.

**Did this work before?**
No, this is the first time I have set VictoriaMetrics as a Datasource.
However, the same error does not occur when Prometheus is set as the Datasource.

### Is the bug inside a dashboard panel?
After setting up VictoriaMetrics in Datasource, you will be taken to a screen where you can set up a new alert rule.

### Environment (with versions)?
OS: Rocky Linux release 9.3
Grafana: 10.2.3
VictoriaMetrics: 1.83.0
GoogleChrome: 120.0.6099.234

### Grafana platform?
I use Opensource.

**Comment by dmitryk-dk** [comment]
I think this is similar issue https://github.com/VictoriaMetrics/grafana-datasource/issues/126. 

Can you downgrade your grafana to version 9.2.2? And check that the error happens

**Comment by ma-bo-panda** [comment]
@dmitryk-dk 
Thanks for your comment.
As you say, it seems to be the same as issue #126. Is this a version-dependent issue?
I will try to verify the downgrade, but can you tell me why 9.2.2 is specified?

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk Thanks for your comment. As you say, it seems to be the same as issue #126. Is this a version-dependent issue? I will try to verify the downgrade, but can you tell me why 9.2.2 is specified?

Hi! I will try to do it with versions 10 and 9 and will check where there can be differences. Maybe Grafana updates some calls in the version 10

**Comment by ma-bo-panda** [comment]
> > @dmitryk-dk Thanks for your comment. As you say, it seems to be the same as issue #126. Is this a version-dependent issue? I will try to verify the downgrade, but can you tell me why 9.2.2 is specified?
> 
> Hi! I will try to do it with versions 10 and 9 and will check where there can be differences. Maybe Grafana updates some calls in the version 10

Thanks for your support.
I checked with 9.5.15, the latest version of Grafana 9 series, and the same error did not occur.

**Comment by hagen1778** [comment]
@dmitryk-dk I was under impression that this datasource doesn't support alerting engine due to reasons explained here https://github.com/VictoriaMetrics/grafana-datasource?tab=readme-ov-file#why-victoriametrics-datasource-doesnt-support-alerting. 
Can we implement /api/v1/eval handler on datasource side?

**Comment by dmitryk-dk** [comment]
This API call was added at 10 major release of the Grafana. I will check how it implemented and how it works

**Comment by dmitryk-dk** [comment]
Hi @ma-bo-panda ! There was an issue in our plugin realization, and we fixed it. the evaluation API works as expected

**Comment by ma-bo-panda** [comment]
@dmitryk-dk 
Thank you for fixing the bug.
I'm waiting for the merge.

**Comment by hagen1778** [comment]
@ma-bo-panda the fix https://github.com/VictoriaMetrics/grafana-datasource/pull/137 was merged and will be the part of the next release.
Meanwhile, you can verify its correctness by compiling the plugin according to the following instructions https://github.com/VictoriaMetrics/grafana-datasource?tab=readme-ov-file#getting-started-development.
