### ISSUE TITLE
Error during data source configuration

### ISSUE THREAD

**Issue by rivalver** [VictoriaMetrics/grafana-datasource#14]
Hello VIctoriaMetrics team.
Getting the error during the attempt of data source configuration.
Grafana version: 8.3.0.

`Cannot read properties of undefined (reading 'Equal') Evaluating https://grafana-beta.some-domain.com/public/plugins/victoriametrics-datasource/module.js Loading plugins/victoriametrics-datasource/module`

<img width="1537" alt="Screenshot 2022-11-08 at 17 30 58" src="https://user-images.githubusercontent.com/8620015/200577871-c2af8f94-9893-4f69-a9da-140a32dffd92.png">

**Comment by Loori-R** [comment]
The bugfix has been included in [victoriametrics-datasource v0.1.1](https://github.com/VictoriaMetrics/grafana-datasource/releases). Closing the issue as fixed.
