### ISSUE TITLE
Query prettifier doesn't work with Grafana variables

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#166]
Try putting the following query in panel:
```
topk_max(10, 
    sum(rate(vmalert_iteration_duration_seconds_sum{job=~"$job", instance=~"$instance", group=~"$group"}[$__rate_interval])) by(job, group))
```
and press Prettify button.

Expected result: query gets prettified
Actual result: `    "msg": "cannot recognize \"$__rate_interval]))by(job, group))\"; unparsed data: \"[$__rate_interval]))by(job, group))\""
`

**Comment by hagen1778** [comment]
@dmitryk-dk I think this involves changes to metricsql Go lib.

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk I think this involves changes to metricsql Go lib.

Ok, i will check it

**Comment by dmitryk-dk** [comment]
@hagen1778 the problem there with Grafana variables. I think we should remove them before executing in a prettify function

**Comment by hagen1778** [comment]
> @hagen1778 the problem there with Grafana variables. I think we should remove them before executing in a prettify function

Would that help to prettify query afterwards? Would you be able to restore the prettified query back by putting variables in it?

**Comment by dmitryk-dk** [comment]
> > @hagen1778 the problem there with Grafana variables. I think we should remove them before executing in a prettify function
> 
> Would that help to prettify query afterwards? Would you be able to restore the prettified query back by putting variables in it?

@hagen1778 i think we should discuss where it is better to handle it. I am not sure that we should handle Grafana variables in the metricsql library

**Comment by dmitryk-dk** [comment]
@hagen1778 I think we can use a static lookbehind window to replace the Grafana variable. Make the query prettier, and then replace the static look behind window with the Grafana variable back. I think this behavior should work well.

**Comment by hagen1778** [comment]
Agree. Do you think it should be handled on front end side?

**Comment by dmitryk-dk** [comment]
> Agree. Do you think it should be handled on front end side?

Checked the code. So the backend just works as a proxy to data source, and there are no handlers to handle this request, and I think it is not necessary to add this handler to the backend. I think the better place to do it is on the front end. The frontend part can manipulate query string on request and response and show the correct results.
