### ISSUE TITLE
Default URL needs to be updated

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#2]
Default URL is set to default Prometheus port.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/2902918/194051053-c4f0590e-67c0-46ce-9831-f3dd38c96bd7.png">

Would be nice to change it to the default VM port `:8428`. 
To the tooltip of this field would be nice to add tips&links how to setup for cluster VM - https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format
Since our docs for cluster version do not contain the exact guide how to configure Grafana - we might need to add it as well. Similar to https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#grafana-setup

**Comment by Loori-R** [comment]
Has been fixed in the commit 6c0c015c25f449149a527fc2edfd14449cd3ca64.
