### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#22]
This repo contains a lot of code borrowed from the Prometheus datasource implementation at https://github.com/grafana/grafana. This violates the license of the Grafana repo https://github.com/grafana/grafana/blob/main/LICENSE.

Workarounds are the following:
1. Re-write the implementation of core functions copied from the Prometheus datasource. Despite both VictoriaMetrics and Prometheus are providing the same HTTP API code still need to be re-written to satisfy the licensing.
2. Change this repo license to the same license as Grafana repo has and explicitly mention the source of copied files.

**Comment by Loori-R** [comment]
The license has been changed in [v0.1.3](https://github.com/VictoriaMetrics/grafana-datasource/releases). Closing the feature request as done.
