### ISSUE TITLE
Change datasource name to `VictoriaMetrics`

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#3]
The name is too long :-)
<img width="405" alt="image" src="https://user-images.githubusercontent.com/2902918/194052710-a4da99e9-8e61-4d3c-aa84-a6bb3cba7c9f.png">

**Comment by Loori-R** [comment]
Has been fixed in the commit 6c0c015c25f449149a527fc2edfd14449cd3ca64.
