### ISSUE TITLE
Show query trace right in Grafana

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#36]
Query panel has a toggler named `Explain` which doesn't seem very useful so far:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/2902918/207369171-284ec876-d78e-4a29-88d0-9e6a7d5c3d7b.png">

What if we replace this toggler with `Trace` functionality, which would send a [trace request](https://docs.victoriametrics.com/#query-tracing) to VictoriaMetrics and render the output next to the query panel?

Alternatively, we can try using `QueryInspector` panel for showing query trace.

**Comment by Loori-R** [comment]
This feature is available starting from [v0.1.3](https://github.com/VictoriaMetrics/grafana-datasource/releases). Closing the feature request as done.
