### ISSUE TITLE
Variable requests do not respect the time range filter

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#47]
When loading Grafana dash with VM DS I notice that requests to `/api/v1/series` used by dashboard variable requests do not respect the selected time range:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2902918/211271791-cc460e1d-44f4-47b8-a89a-be88f770e773.png">

When refreshing the dash I see the following requests in console:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/2902918/211271901-27f5001a-0056-4dc2-82c3-ca55d181dc75.png">
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/2902918/211271935-9d5351ea-8bb9-4775-8b9e-b82c76c5272c.png">

Note the difference in start/end params for both queries.

**Comment by Loori-R** [comment]
The bugfix has been included in [v0.1.3](https://github.com/VictoriaMetrics/grafana-datasource/releases). Closing the issue as fixed.

**Comment by tenmozes** [comment]
@zoadsa please provide the context how to reproduce the bug

**Comment by hagen1778** [comment]
The issue supposed to be addressed in https://github.com/VictoriaMetrics/grafana-datasource/pull/81 and will be included into the next release.
