### ISSUE TITLE
Make the logo inside the white circle a bit bigger

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#5]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/2902918/195102831-df69b01e-ef96-486b-8a48-00df75b9bc66.png">

I think we can expand the logo in white circle so it fills more space within it.

**Comment by Loori-R** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/29711459/195462491-fad6f68c-571e-4612-8973-e108fb1edad9.png">

1162b1f442af6ac984360cbbf6cf446698509a1d
