### ISSUE TITLE
Feature: Query Raw data 

### ISSUE THREAD

**Issue by TomasVojacek** [VictoriaMetrics/grafana-datasource#50]
We are using victoria-metric for event logs.
event{eventType="1",deviceId="abcd"} 1 
Data are spare. 
We need display all raw sample for deviceId="abcd" and keep original timestamp. If query return too much data, we need to truncate result instead of grouping.
query_range round timestamp and group date according interval.
Would it be possible to do query on /export api as alternative to query_range?
I'm aware that export api use different syntax and is more limited.

**Comment by f41gh7** [comment]
@hagen1778  WDYT?

**Comment by hagen1778** [comment]
Hi @TomasVojacek! You can get raw data right in Grafana with the following query:
```
event{eventType="1",deviceId="abcd"}[1m]
```
This query ^ will return raw values for the last 1m when sent to /query API
see example [here](https://play-grafana.victoriametrics.com/explore?orgId=2&left=%7B%22datasource%22:%22VictoriaMetrics_demo%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22up%5B1m%5D%22,%22editorMode%22:%22code%22,%22range%22:false,%22instant%22:true,%22format%22:%22table%22,%22exemplar%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D).
