### ISSUE TITLE
Legend Auto doesn't drop common labels

### ISSUE THREAD

**Issue by kkolyan** [VictoriaMetrics/grafana-datasource#55]
As I understand, Auto legend mode should drop common labels and leave only unique. In this example, "host" is common label, but it's present in each timeseries legend.

![image (1)](https://user-images.githubusercontent.com/3194236/223421936-9292633d-992a-4cce-847c-2c2f25514af4.png)

**Comment by proffust** [comment]
grafana-server -v
Version 9.3.6 (commit: 978237e7cb, branch: HEAD)
 grafana-cli plugins ls
installed plugins:
ae3e-plotly-panel @ 0.5.0
agenty-flowcharting-panel @ 0.9.1
bessler-pictureit-panel @ 1.0.1
blackmirror1-singlestat-math-panel @ 1.1.8
grafana-clock-panel @ 2.1.3
grafana-piechart-panel @ 1.6.4
grafana-worldmap-panel @ 1.0.3
knightss27-weathermap-panel @ 0.3.5
marcusolsson-json-datasource @ 1.3.2
victoriametrics-datasource @ 0.1.2
vonage-status-panel @ 1.0.11

**Comment by dmitryk-dk** [comment]
Hi ! When you set auto labels it shows all values for datapoints. So I think this is not a bug

**Comment by hagen1778** [comment]
Closing as inactive
