### ISSUE TITLE
Grafana's query builder doesn't have MetricsQL funcs

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#66]
Grafana allows to use query builder for compiling the query. In the builder user can choose which functions to apply. It is expected that builder would have MetricsQL functions available for search and in list:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/2902918/228543023-1aa87ca8-b6c8-4f67-a507-a0b4754ca013.png">

**Comment by Loori-R** [comment]
This feature is available starting from [v0.2.0](https://github.com/VictoriaMetrics/grafana-datasource/releases). Closing the feature request as done.

**Comment by Karsonito** [comment]
Hello!

The builder doesn't work with MetricsQL functions yet?
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/2379481/245bb452-d25f-420e-bf8c-d3425abc8e6c)

Similar problem with code=>builder parser?
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/2379481/dac8c39e-b2a9-4625-b28a-ee0d17ac8f0e)
Although code mode better informed in MetricsQL
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/2379481/b3c54646-3ce2-44e4-83cb-67760909116f)

**Comment by hagen1778** [comment]
@Loori-R would you mind taking a look pls?

> BTW please add links to MetricsQL functions to https://docs.victoriametrics.com/MetricsQL.html

Do you mean add link to docs in Grafana interface?

**Comment by Loori-R** [comment]
Indeed, some functions are not working correctly. We have reopened the issue to address this problem.

**Comment by Karsonito** [comment]
> Do you mean add link to docs in Grafana interface?
yes

**Comment by Loori-R** [comment]
The bugfix has been included in [victoriametrics-datasource v0.4.0](https://github.com/VictoriaMetrics/grafana-datasource/releases).
