### ISSUE TITLE
[FEATURE]: add support for windows OS

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/grafana-datasource#67]
VictoriaMetrics grafana-datasource has builds for darwin and linux and it will be nice to get windows support too because windows support is almost done - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70

**Comment by dmitryk-dk** [comment]
The issue was implemented and included in the [v0.5.0](https://github.com/VictoriaMetrics/grafana-datasource/releases/tag/v0.5.0) release
