### ISSUE TITLE
includes in plugin.json

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#7]
plugin.json contains `includes` section. Do we need it? Should it be removed?

**Comment by Loori-R** [comment]
For now, we don't need it. Has been removed in the commit [57f3712](https://github.com/VictoriaMetrics/grafana-datasource/pull/9/commits/57f3712c2e1b46d55d0f5e52441666a539ca9e3f).

Additional resources like dashboard, page, panel, data source.
[Grafana docs](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#includes).
For example:
<img width=400 src="https://user-images.githubusercontent.com/29711459/195904508-0716acde-0259-41d8-a903-87245d147d5e.png"/>
