### ISSUE TITLE
Prompt for 404 error when configuring the data source

### ISSUE THREAD

**Issue by zxlxgd** [VictoriaMetrics/grafana-datasource#76]
Fetch error: 404 Instantiating https://yy.qihoo.net/grafana/public/@emotion/css Loading https://yy.qihoo.net/grafana/public/plugins/victoriametrics-datasource/module.js Loading plugins/victoriametrics-datasource/module

![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/10458088/71d7c520-f322-4854-ad53-cb054fbaab41)

grafana version: 7.5.11
plugin-version: 0.1.3

**Comment by hagen1778** [comment]
@zxlxgd is the issue still relevant for you?

**Comment by dmitryk-dk** [comment]
Close because of lack of activity
