### ISSUE TITLE
Remove promql cheat sheet

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#8]
It is unlikely someone actually using it

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/2902918/195874730-d6033bcd-f6ef-494a-a8cc-9af7f9429e03.png">

**Comment by Loori-R** [comment]
Has been removed in the commit [5c9b55a](https://github.com/VictoriaMetrics/grafana-datasource/pull/9/commits/5c9b55adddd3002a692afeeaefe9ec49f7b24610)
