### ISSUE TITLE
Label names duplicated in legend when expression is used in panel

### ISSUE THREAD

**Issue by gautamg795** [VictoriaMetrics/grafana-datasource#93]
This is a weird bug that so far, I've only been able to track down to the VictoriaMetrics datasource -- the issue disappears when using the Prometheus datasource, and does not occur if the panel doesn't contain an "expression". 

This is the desired panel output, when using the Prometheus datasource:
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/3837919/dab6809e-e845-491a-8e44-5ceab6ce93e4)

However switching to the VictoriaMetrics datasource makes the legend look like this:
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/3837919/c4912ccc-c806-4ce4-93e1-8b22a14b79d1)
Every legend entry is duplicated!

Attempting to set the legends back to "auto" didn't work either, and I end up with `__auto __auto`
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/3837919/023a5555-4122-48e7-9b1b-ae6b39d2b227)

**Comment by hagen1778** [comment]
@Loori-R I see that https://github.com/VictoriaMetrics/grafana-datasource/pull/97 was merged and released. Does it mean we can close the issue?

**Comment by Loori-R** [comment]
The bugfix has been included in [victoriametrics-datasource v0.4.0](https://github.com/VictoriaMetrics/grafana-datasource/releases).
