### ISSUE TITLE
No data when passing label values with dot from variable

### ISSUE THREAD

**Issue by p4k8** [VictoriaMetrics/grafana-datasource#94]
VM datasource version: 0.2.1
Grafana version: 10.0.2
VM cluster version: 1.91.3

If label's value has a dot symbol (for example, `ip_address="10.0.0.1"` or `interface="GigabitEthernet0/1.1"`) and it is being passed to the dashboard from variable with `label_values()`, no data will be returned. At the same time, Inspect tab shows tag value with added `\\\\` before the dot symbol (for example, `ip_address=\"10\\\\.0\\\\.0\\\\.1\"`). 

If you specify tag value without using variables, it is rendered in Inspect tab like `ip_address=\"10.0.0.1\"`.

**Comment by hagen1778** [comment]
@Loori-R could you please take a look?

**Comment by p4k8** [comment]
Can't reproduce as well after upgrading datasource to 0.3.0.
I guess this can be closed then. Thank you!
