### ISSUE TITLE
annotation queries do not respect `Custom query parameters`

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/grafana-datasource#95]
To reproduce:
Configure VM datasource with custom query params:
<img width="462" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/2902918/d60f0707-c234-406c-b30f-2eaec077112d">

All queries now supposed to filter metrics with `job=vmalert`.

Try plotting a panel to verify:
<img width="844" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/2902918/8497ee3b-3c83-4b0a-8f2f-11cb23523eab">

it works.

Add an annotation query:
<img width="550" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/2902918/6ec88f80-8889-4239-acdd-923e95d350b0">

Try plotting it on the panel:
<img width="841" alt="image" src="https://github.com/VictoriaMetrics/grafana-datasource/assets/2902918/a8915619-f9fe-4a49-9f86-4caf8217f68e">

It shows unflitered data.

**Comment by hagen1778** [comment]
@Loori-R thanks for PR! Can we make a release?

**Comment by Loori-R** [comment]
The bugfix has been included in [victoriametrics-datasource v0.4.0](https://github.com/VictoriaMetrics/grafana-datasource/releases).
