### ISSUE TITLE
Metrics browser "no metrics found"

### ISSUE THREAD

**Issue by zoadsa** [VictoriaMetrics/grafana-datasource#98]
Grafana Version 9.3.6 (commit: 978237e7cb, branch: HEAD)
victoriametrics-datasource @ 0.3.0

There is strange behavior with the metrics browser in Grafana Explore. It seems to be a bug in the VictoriaMetrics datasource plugin, as the Prometheus datasource plugin doesn't have this issue.

Steps to reproduce:
1) Open Grafana Explore and select any VictoriaMetrics datasource. You will see "no metrics found" in the metrics browser. There are no errors in browser console.
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/133942298/53e955cc-d964-4f47-8b8f-8d2ebe7cb215)
2) Change the time interval **twice**, and now the metrics will be available in the metrics browser.
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/133942298/955b136e-d8ce-4f2e-8ceb-3f71e842bce3)
![image](https://github.com/VictoriaMetrics/grafana-datasource/assets/133942298/642afa3e-07ed-4ba4-9f1d-19727756641a)

**Comment by Loori-R** [comment]
The bugfix has been included in [victoriametrics-datasource v0.4.0](https://github.com/VictoriaMetrics/grafana-datasource/releases).
